# Generated by Django 4.2.1 on 2023-06-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=7, max_digits=15)),
                ('price_purchased', models.DecimalField(decimal_places=2, max_digits=15)),
                ('number_of_coin', models.DecimalField(decimal_places=7, max_digits=15)),
                ('coin', models.CharField(max_length=3)),
                ('buy_date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
